run:
  dir: ${paths.log_dir}/anomaly_detect/runs/${now:%Y-%m-%d_%H-%M-%S}

sweep:
  dir: ${paths.log_dir}/anomaly_detect/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      filename: ${hydra:runtime.output_dir}/anomaly_detect.log
